### ISSUE TITLE
Would be nice to see any simple usage in README

### ISSUE THREAD

**Issue by aahutsal** [royharoush/rtools#1]
Got the idea. Looks good. But absolutely unsure how to use your parser scripts. Could you explain please?

**Comment by royharoush** [comment]
hi @gutsal-arsen ,
the script nmapParseClean.sh combines a few parsing scripts and post processing actions on  multiple nmap output files (gnmap,nmap and xml). it is mostly intended for (pseudo) "big data" handling (X000,000) of scan outputs. When you run the script in a folder with nmap output files (you should have xml and gnmap, as nmap files are too annoying to parse and are ignored), the script will work on them without the need of providing any additional user input. 
you can do the following, on your kali machine:

```
nmap 127.0.0.1 --top-ports 5000 -oA test
wget https://github.com/royharoush/rtools/blob/master/nmaParseClean.sh  && bash nmaParseClean.sh

```

you can follow the output, its very descriptive. the script itself also has alot of comments in it to explain how it works. 
I might take the time next week to add additional info for it. 

Also, if you are talking about the gnx and and gnmaparser scripts, they have their own contextual helps menus (--help), and they were not built by me (slightly modified), though their license information is in tact and you can find the original authors.
Hope that helps.

**Comment by aahutsal** [comment]
Thank you. Will try and get back to you.

**Comment by royharoush** [comment]
created readme
